version: "3.8"
services:
  node_backend:
    container_name: node_server
    image: node_server:0.0.1
    build:
      context: .
    restart: always
    ports:
      - 80:80
    environment:
      - PORT=80
      - DB_NAME=rating
      - DB_USER=postgres
      - DB_PASSWORD=1976
      - DB_HOST=node_db
    command: npm run dev
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:14"
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1976
      - POSTGRES_DB=rating
    volumes:
      - nps_data:/var/lib/postgresql/data
    restart: always
volumes:
  nps_data: {}
