version: '3'
services:
  database:
    container_name: database
    image: 'postgres:14'
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1976
      - POSTGRES_DB=rating
    volumes:
      - nps_data:/var/lib/postgresql/data
    restart: always
  server:
    container_name: server
    platform: linux/amd64
    build:
      context: .
    restart: always
    ports:
      - 80:80
    environment:
      - DB_NAME=rating
      - DB_USER=postgres
      - DB_PASSWORD=1976
      - DB_HOST=database
    links:
      - database
    volumes:
      - /app/node_modules
      - ./:/app
volumes:
  nps_data: {}
